export const LINE_DEFINITIONS = {
    ginza: { code: 'G', name: '銀座線', color: '#f39700' },
    marunouchi: { code: 'M', name: '丸ノ内線', color: '#e60012' },
    hibiya: { code: 'H', name: '日比谷線', color: '#9caeb7' },
    tozai: { code: 'T', name: '東西線', color: '#00a7db' },
    chiyoda: { code: 'C', name: '千代田線', color: '#00a650' },
    yurakucho: { code: 'Y', name: '有楽町線', color: '#d7c447' },
    hanzomon: { code: 'Z', name: '半蔵門線', color: '#9b7cb6' },
    nanboku: { code: 'N', name: '南北線', color: '#00ada9' },
    fukutoshin: { code: 'F', name: '副都心線', color: '#bb641d' },
} as const;

export type LineId = keyof typeof LINE_DEFINITIONS;

// 東京メトロ公式の50音順を保つため、このオブジェクトは表示順で定義する。
export const STATION_NAMES = {
    'aoyama-itchome': '青山一丁目',
    akasaka: '赤坂',
    'akasaka-mitsuke': '赤坂見附',
    'akabane-iwabuchi': '赤羽岩淵',
    akihabara: '秋葉原',
    asakusa: '浅草',
    'azabu-juban': '麻布十番',
    ayase: '綾瀬',
    awajicho: '淡路町',
    iidabashi: '飯田橋',
    ikebukuro: '池袋',
    ichigaya: '市ケ谷',
    inaricho: '稲荷町',
    iriya: '入谷',
    ueno: '上野',
    'ueno-hirokoji': '上野広小路',
    urayasu: '浦安',
    edogawabashi: '江戸川橋',
    ebisu: '恵比寿',
    oji: '王子',
    'oji-kamiya': '王子神谷',
    otemachi: '大手町',
    ogikubo: '荻窪',
    oshiage: '押上〈スカイツリー前〉',
    ochiai: '落合',
    ochanomizu: '御茶ノ水',
    'omote-sando': '表参道',
    kagurazaka: '神楽坂',
    kasai: '葛西',
    kasumigaseki: '霞ケ関',
    kanamecho: '要町',
    kamiyacho: '神谷町',
    kayabacho: '茅場町',
    kanda: '神田',
    gaiemmae: '外苑前',
    'kita-ayase': '北綾瀬',
    'kita-sando': '北参道',
    'kita-senju': '北千住',
    kiba: '木場',
    kyobashi: '京橋',
    'kiyosumi-shirakawa': '清澄白河',
    kinshicho: '錦糸町',
    gyotoku: '行徳',
    ginza: '銀座',
    'ginza-itchome': '銀座一丁目',
    kudanshita: '九段下',
    kojimachi: '麴町',
    korakuen: '後楽園',
    'kotake-mukaihara': '小竹向原',
    'kokkai-gijidomae': '国会議事堂前',
    kodemmacho: '小伝馬町',
    komagome: '駒込',
    gokokuji: '護国寺',
    sakuradamon: '桜田門',
    shibuya: '渋谷',
    shimo: '志茂',
    'shirokane-takanawa': '白金高輪',
    shirokanedai: '白金台',
    'shin-otsuka': '新大塚',
    'shin-ochanomizu': '新御茶ノ水',
    'shin-kiba': '新木場',
    'shin-koenji': '新高円寺',
    shinjuku: '新宿',
    'shinjuku-gyoemmae': '新宿御苑前',
    'shinjuku-sanchome': '新宿三丁目',
    shintomicho: '新富町',
    'shin-nakano': '新中野',
    shimbashi: '新橋',
    jimbocho: '神保町',
    suitengumae: '水天宮前',
    suehirocho: '末広町',
    sumiyoshi: '住吉',
    senkawa: '千川',
    sendagi: '千駄木',
    zoshigaya: '雑司が谷',
    takadanobaba: '高田馬場',
    takebashi: '竹橋',
    tatsumi: '辰巳',
    'tameike-sanno': '溜池山王',
    tawaramachi: '田原町',
    'chikatetsu-akatsuka': '地下鉄赤塚',
    'chikatetsu-narimasu': '地下鉄成増',
    tsukishima: '月島',
    tsukiji: '築地',
    tokyo: '東京',
    todaimae: '東大前',
    toyocho: '東陽町',
    toyosu: '豊洲',
    toranomon: '虎ノ門',
    'toranomon-hills': '虎ノ門ヒルズ',
    'naka-okachimachi': '仲御徒町',
    nakano: '中野',
    'nakano-sakaue': '中野坂上',
    'nakano-shimbashi': '中野新橋',
    'nakano-fujimicho': '中野富士見町',
    'naka-meguro': '中目黒',
    nagatacho: '永田町',
    'nishi-kasai': '西葛西',
    nishigahara: '西ケ原',
    'nishi-shinjuku': '西新宿',
    'nishi-nippori': '西日暮里',
    'nishi-funabashi': '西船橋',
    'nishi-waseda': '西早稲田',
    nijubashimae: '二重橋前〈丸の内〉',
    nihombashi: '日本橋',
    ningyocho: '人形町',
    nezu: '根津',
    nogizaka: '乃木坂',
    hatchobori: '八丁堀',
    hanzomon: '半蔵門',
    'baraki-nakayama': '原木中山',
    hikawadai: '氷川台',
    'higashi-ikebukuro': '東池袋',
    'higashi-ginza': '東銀座',
    'higashi-koenji': '東高円寺',
    'higashi-shinjuku': '東新宿',
    hibiya: '日比谷',
    'hiro-o': '広尾',
    heiwadai: '平和台',
    honancho: '方南町',
    'hon-komagome': '本駒込',
    'hongo-sanchome': '本郷三丁目',
    machiya: '町屋',
    mitsukoshimae: '三越前',
    'minami-asagaya': '南阿佐ケ谷',
    'minami-gyotoku': '南行徳',
    'minami-sunamachi': '南砂町',
    'minami-senju': '南千住',
    minowa: '三ノ輪',
    myogadani: '茗荷谷',
    myoden: '妙典',
    'meiji-jingumae': '明治神宮前〈原宿〉',
    meguro: '目黒',
    'monzen-nakacho': '門前仲町',
    yurakucho: '有楽町',
    yushima: '湯島',
    yotsuya: '四ツ谷',
    'yotsuya-sanchome': '四谷三丁目',
    'yoyogi-uehara': '代々木上原',
    'yoyogi-koen': '代々木公園',
    roppongi: '六本木',
    'roppongi-itchome': '六本木一丁目',
    wakoshi: '和光市',
    waseda: '早稲田',
} as const;

export type StationId = keyof typeof STATION_NAMES;

/** 旅客営業規程第13条に定められた、隣接駅間の運賃計算キロ程（0.1km単位）。 */
export const FARE_CALCULATION_DISTANCE_OVERRIDES = [
    ['ayase', 'kita-senju', 25],
    ['hibiya', 'kasumigaseki', 12],
    ['kasumigaseki', 'kokkai-gijidomae', 7],
    ['aoyama-itchome', 'nagatacho', 13],
    ['kotake-mukaihara', 'senkawa', 10],
    ['kanamecho', 'ikebukuro', 12],
    ['tameike-sanno', 'toranomon', 6],
    ['akasaka-mitsuke', 'tameike-sanno', 9],
    ['tameike-sanno', 'nagatacho', 9],
    ['nagatacho', 'yotsuya', 13],
    ['shibuya', 'omote-sando', 13],
] as const satisfies ReadonlyArray<readonly [StationId, StationId, number]>;

type LinePathDefinition = {
    lineId: LineId;
    /** 各タプルの数値は直前駅からの営業キロを0.1km単位で表す。 */
    stations: ReadonlyArray<readonly [StationId, number]>;
};

export const LINE_PATHS = [
    {
        lineId: 'ginza',
        stations: [
            ['shibuya', 0],
            ['omote-sando', 12],
            ['gaiemmae', 7],
            ['aoyama-itchome', 7],
            ['akasaka-mitsuke', 13],
            ['tameike-sanno', 7],
            ['toranomon', 8],
            ['shimbashi', 8],
            ['ginza', 9],
            ['kyobashi', 7],
            ['nihombashi', 7],
            ['mitsukoshimae', 6],
            ['kanda', 7],
            ['suehirocho', 11],
            ['ueno-hirokoji', 6],
            ['ueno', 5],
            ['inaricho', 7],
            ['tawaramachi', 7],
            ['asakusa', 8],
        ],
    },
    {
        lineId: 'marunouchi',
        stations: [
            ['ogikubo', 0],
            ['minami-asagaya', 15],
            ['shin-koenji', 12],
            ['higashi-koenji', 9],
            ['shin-nakano', 10],
            ['nakano-sakaue', 11],
            ['nishi-shinjuku', 11],
            ['shinjuku', 8],
            ['shinjuku-sanchome', 3],
            ['shinjuku-gyoemmae', 7],
            ['yotsuya-sanchome', 9],
            ['yotsuya', 10],
            ['akasaka-mitsuke', 13],
            ['kokkai-gijidomae', 9],
            ['kasumigaseki', 7],
            ['ginza', 10],
            ['tokyo', 11],
            ['otemachi', 6],
            ['awajicho', 9],
            ['ochanomizu', 8],
            ['hongo-sanchome', 8],
            ['korakuen', 8],
            ['myogadani', 18],
            ['shin-otsuka', 12],
            ['ikebukuro', 18],
        ],
    },
    {
        lineId: 'marunouchi',
        stations: [
            ['honancho', 0],
            ['nakano-fujimicho', 13],
            ['nakano-shimbashi', 6],
            ['nakano-sakaue', 13],
        ],
    },
    {
        lineId: 'hibiya',
        stations: [
            ['naka-meguro', 0],
            ['ebisu', 10],
            ['hiro-o', 15],
            ['roppongi', 17],
            ['kamiyacho', 15],
            ['toranomon-hills', 5],
            ['kasumigaseki', 8],
            ['hibiya', 12],
            ['ginza', 4],
            ['higashi-ginza', 4],
            ['tsukiji', 6],
            ['hatchobori', 10],
            ['kayabacho', 5],
            ['ningyocho', 9],
            ['kodemmacho', 6],
            ['akihabara', 9],
            ['naka-okachimachi', 10],
            ['ueno', 5],
            ['iriya', 12],
            ['minowa', 12],
            ['minami-senju', 8],
            ['kita-senju', 21],
        ],
    },
    {
        lineId: 'tozai',
        stations: [
            ['nakano', 0],
            ['ochiai', 20],
            ['takadanobaba', 19],
            ['waseda', 17],
            ['kagurazaka', 12],
            ['iidabashi', 12],
            ['kudanshita', 7],
            ['takebashi', 10],
            ['otemachi', 10],
            ['nihombashi', 8],
            ['kayabacho', 5],
            ['monzen-nakacho', 18],
            ['kiba', 11],
            ['toyocho', 9],
            ['minami-sunamachi', 12],
            ['nishi-kasai', 27],
            ['kasai', 12],
            ['urayasu', 19],
            ['minami-gyotoku', 12],
            ['gyotoku', 15],
            ['myoden', 13],
            ['baraki-nakayama', 21],
            ['nishi-funabashi', 19],
        ],
    },
    {
        lineId: 'chiyoda',
        stations: [
            ['yoyogi-uehara', 0],
            ['yoyogi-koen', 10],
            ['meiji-jingumae', 12],
            ['omote-sando', 9],
            ['nogizaka', 14],
            ['akasaka', 11],
            ['kokkai-gijidomae', 8],
            ['kasumigaseki', 8],
            ['hibiya', 8],
            ['nijubashimae', 7],
            ['otemachi', 7],
            ['shin-ochanomizu', 13],
            ['yushima', 12],
            ['nezu', 12],
            ['sendagi', 10],
            ['nishi-nippori', 9],
            ['machiya', 17],
            ['kita-senju', 26],
            ['ayase', 26],
            ['kita-ayase', 21],
        ],
    },
    {
        lineId: 'yurakucho',
        stations: [
            ['wakoshi', 0],
            ['chikatetsu-narimasu', 22],
            ['chikatetsu-akatsuka', 14],
            ['heiwadai', 18],
            ['hikawadai', 14],
            ['kotake-mukaihara', 15],
            ['senkawa', 10],
            ['kanamecho', 10],
            ['ikebukuro', 12],
            ['higashi-ikebukuro', 9],
            ['gokokuji', 11],
            ['edogawabashi', 13],
            ['iidabashi', 16],
            ['ichigaya', 11],
            ['kojimachi', 9],
            ['nagatacho', 9],
            ['sakuradamon', 9],
            ['yurakucho', 10],
            ['ginza-itchome', 5],
            ['shintomicho', 7],
            ['tsukishima', 13],
            ['toyosu', 14],
            ['tatsumi', 17],
            ['shin-kiba', 15],
        ],
    },
    {
        lineId: 'hanzomon',
        stations: [
            ['shibuya', 0],
            ['omote-sando', 13],
            ['aoyama-itchome', 14],
            ['nagatacho', 14],
            ['hanzomon', 10],
            ['kudanshita', 16],
            ['jimbocho', 4],
            ['otemachi', 17],
            ['mitsukoshimae', 7],
            ['suitengumae', 13],
            ['kiyosumi-shirakawa', 17],
            ['sumiyoshi', 19],
            ['kinshicho', 10],
            ['oshiage', 14],
        ],
    },
    {
        lineId: 'nanboku',
        stations: [
            ['meguro', 0],
            ['shirokanedai', 13],
            ['shirokane-takanawa', 10],
            ['azabu-juban', 13],
            ['roppongi-itchome', 12],
            ['tameike-sanno', 9],
            ['nagatacho', 7],
            ['yotsuya', 15],
            ['ichigaya', 10],
            ['iidabashi', 11],
            ['korakuen', 14],
            ['todaimae', 13],
            ['hon-komagome', 9],
            ['komagome', 14],
            ['nishigahara', 14],
            ['oji', 10],
            ['oji-kamiya', 12],
            ['shimo', 16],
            ['akabane-iwabuchi', 11],
        ],
    },
    {
        lineId: 'fukutoshin',
        stations: [
            ['wakoshi', 0],
            ['chikatetsu-narimasu', 22],
            ['chikatetsu-akatsuka', 14],
            ['heiwadai', 18],
            ['hikawadai', 14],
            ['kotake-mukaihara', 15],
            ['senkawa', 11],
            ['kanamecho', 10],
            ['ikebukuro', 9],
            ['zoshigaya', 18],
            ['nishi-waseda', 15],
            ['higashi-shinjuku', 9],
            ['shinjuku-sanchome', 11],
            ['kita-sando', 14],
            ['meiji-jingumae', 12],
            ['shibuya', 10],
        ],
    },
] satisfies ReadonlyArray<LinePathDefinition>;

export type TransferType = 'inside' | 'outside';

export type CrossStationTransfer = {
    fromStationId: StationId;
    toStationId: StationId;
    linePairs: ReadonlyArray<readonly [LineId, LineId]>;
    type: TransferType;
};

export const SAME_STATION_OUTSIDE_TRANSFERS = [
    ['ueno', 'ginza', 'hibiya'],
    ['mitsukoshimae', 'ginza', 'hanzomon'],
    ['otemachi', 'marunouchi', 'tozai'],
    ['otemachi', 'marunouchi', 'chiyoda'],
    ['otemachi', 'marunouchi', 'hanzomon'],
    ['otemachi', 'tozai', 'chiyoda'],
    ['otemachi', 'tozai', 'hanzomon'],
    ['otemachi', 'chiyoda', 'hanzomon'],
    ['ikebukuro', 'marunouchi', 'fukutoshin'],
    ['ikebukuro', 'marunouchi', 'yurakucho'],
    ['ikebukuro', 'fukutoshin', 'yurakucho'],
    ['iidabashi', 'tozai', 'yurakucho'],
    ['iidabashi', 'tozai', 'nanboku'],
    ['shibuya', 'ginza', 'fukutoshin'],
    ['shinjuku-sanchome', 'marunouchi', 'fukutoshin'],
] as const satisfies ReadonlyArray<readonly [StationId, LineId, LineId]>;

export const CROSS_STATION_TRANSFERS = [
    {
        fromStationId: 'akasaka-mitsuke',
        toStationId: 'nagatacho',
        linePairs: [
            ['ginza', 'yurakucho'],
            ['ginza', 'hanzomon'],
            ['ginza', 'nanboku'],
            ['marunouchi', 'yurakucho'],
            ['marunouchi', 'hanzomon'],
            ['marunouchi', 'nanboku'],
        ],
        type: 'inside',
    },
    {
        fromStationId: 'tameike-sanno',
        toStationId: 'kokkai-gijidomae',
        linePairs: [
            ['ginza', 'marunouchi'],
            ['ginza', 'chiyoda'],
            ['nanboku', 'marunouchi'],
            ['nanboku', 'chiyoda'],
        ],
        type: 'inside',
    },
    {
        fromStationId: 'ueno-hirokoji',
        toStationId: 'naka-okachimachi',
        linePairs: [['ginza', 'hibiya']],
        type: 'outside',
    },
    {
        fromStationId: 'hibiya',
        toStationId: 'yurakucho',
        linePairs: [
            ['hibiya', 'yurakucho'],
            ['chiyoda', 'yurakucho'],
        ],
        type: 'outside',
    },
    {
        fromStationId: 'awajicho',
        toStationId: 'shin-ochanomizu',
        linePairs: [['marunouchi', 'chiyoda']],
        type: 'outside',
    },
    {
        fromStationId: 'ningyocho',
        toStationId: 'suitengumae',
        linePairs: [['hibiya', 'hanzomon']],
        type: 'outside',
    },
    {
        fromStationId: 'tsukiji',
        toStationId: 'shintomicho',
        linePairs: [['hibiya', 'yurakucho']],
        type: 'outside',
    },
    {
        fromStationId: 'ginza',
        toStationId: 'ginza-itchome',
        linePairs: [
            ['ginza', 'yurakucho'],
            ['marunouchi', 'yurakucho'],
            ['hibiya', 'yurakucho'],
        ],
        type: 'outside',
    },
    {
        fromStationId: 'toranomon',
        toStationId: 'toranomon-hills',
        linePairs: [['ginza', 'hibiya']],
        type: 'outside',
    },
] as const satisfies ReadonlyArray<CrossStationTransfer>;
