import type { PrefectureCode } from '@/lib/prefectures';

export interface JapanAirport {
    officialName: string;
    aliases: string[];
    icaoCode: string;
    iataCode: string | null;
    prefectureCode: PrefectureCode;
}

/**
 * 日本の飛行場・空港データ
 *
 * 配列は都道府県コード昇順、同一都道府県内では ICAO 空港コード昇順で管理する。
 * データを追加・更新する際も、このソート順を維持した状態で並べておくこと。
 */
export const japanAirports = [
    { officialName: '旭川飛行場', aliases: [], icaoCode: 'RJCA', iataCode: null, prefectureCode: '01' },
    { officialName: '帯広空港', aliases: [], icaoCode: 'RJCB', iataCode: 'OBO', prefectureCode: '01' },
    { officialName: '新千歳空港', aliases: [], icaoCode: 'RJCC', iataCode: 'CTS', prefectureCode: '01' },
    { officialName: '函館空港', aliases: [], icaoCode: 'RJCH', iataCode: 'HKD', prefectureCode: '01' },
    {
        officialName: '千歳飛行場',
        aliases: [],
        icaoCode: 'RJCJ',
        iataCode: null,
        prefectureCode: '01',
    },
    { officialName: '釧路空港', aliases: [], icaoCode: 'RJCK', iataCode: 'KUH', prefectureCode: '01' },
    { officialName: '女満別空港', aliases: [], icaoCode: 'RJCM', iataCode: 'MMB', prefectureCode: '01' },
    { officialName: '中標津空港', aliases: [], icaoCode: 'RJCN', iataCode: 'SHB', prefectureCode: '01' },
    {
        officialName: '札幌飛行場',
        aliases: ['丘珠空港'],
        icaoCode: 'RJCO',
        iataCode: 'OKD',
        prefectureCode: '01',
    },
    { officialName: '礼文空港', aliases: [], icaoCode: 'RJCR', iataCode: 'RBJ', prefectureCode: '01' },
    { officialName: '計根別着陸場', aliases: [], icaoCode: 'RJCS', iataCode: null, prefectureCode: '01' },
    { officialName: '十勝飛行場', aliases: [], icaoCode: 'RJCT', iataCode: null, prefectureCode: '01' },
    { officialName: '稚内空港', aliases: [], icaoCode: 'RJCW', iataCode: 'WKJ', prefectureCode: '01' },
    { officialName: '八雲飛行場', aliases: [], icaoCode: 'RJCY', iataCode: null, prefectureCode: '01' },
    { officialName: '紋別空港', aliases: [], icaoCode: 'RJEB', iataCode: 'MBE', prefectureCode: '01' },
    { officialName: '旭川空港', aliases: [], icaoCode: 'RJEC', iataCode: 'AKJ', prefectureCode: '01' },
    { officialName: '奥尻空港', aliases: [], icaoCode: 'RJEO', iataCode: 'OIR', prefectureCode: '01' },
    { officialName: '利尻空港', aliases: [], icaoCode: 'RJER', iataCode: 'RIS', prefectureCode: '01' },
    { officialName: '青森空港', aliases: [], icaoCode: 'RJSA', iataCode: 'AOJ', prefectureCode: '02' },
    { officialName: '八戸飛行場', aliases: [], icaoCode: 'RJSH', iataCode: null, prefectureCode: '02' },
    {
        officialName: '三沢飛行場',
        aliases: ['三沢空港'],
        icaoCode: 'RJSM',
        iataCode: 'MSJ',
        prefectureCode: '02',
    },
    { officialName: '大湊飛行場', aliases: [], icaoCode: 'RJSO', iataCode: null, prefectureCode: '02' },
    { officialName: '花巻空港', aliases: [], icaoCode: 'RJSI', iataCode: 'HNA', prefectureCode: '03' },
    { officialName: '仙台空港', aliases: [], icaoCode: 'RJSS', iataCode: 'SDJ', prefectureCode: '04' },
    { officialName: '松島飛行場', aliases: [], icaoCode: 'RJST', iataCode: null, prefectureCode: '04' },
    { officialName: '霞目飛行場', aliases: [], icaoCode: 'RJSU', iataCode: null, prefectureCode: '04' },
    { officialName: '秋田空港', aliases: [], icaoCode: 'RJSK', iataCode: 'AXT', prefectureCode: '05' },
    { officialName: '大館能代空港', aliases: [], icaoCode: 'RJSR', iataCode: 'ONJ', prefectureCode: '05' },
    { officialName: '山形空港', aliases: [], icaoCode: 'RJSC', iataCode: 'GAJ', prefectureCode: '06' },
    { officialName: '庄内空港', aliases: [], icaoCode: 'RJSY', iataCode: 'SYO', prefectureCode: '06' },
    { officialName: '福島空港', aliases: [], icaoCode: 'RJSF', iataCode: 'FKS', prefectureCode: '07' },
    { officialName: '百里飛行場', aliases: ['茨城空港'], icaoCode: 'RJAH', iataCode: 'IBR', prefectureCode: '08' },
    { officialName: '霞ヶ浦飛行場', aliases: [], icaoCode: 'RJAK', iataCode: null, prefectureCode: '08' },
    {
        officialName: '宇都宮飛行場',
        aliases: [],
        icaoCode: 'RJTU',
        iataCode: null,
        prefectureCode: '09',
    },
    {
        officialName: '相馬原飛行場',
        aliases: [],
        icaoCode: 'RJTS',
        iataCode: null,
        prefectureCode: '10',
    },
    { officialName: 'ホンダエアポート', aliases: [], icaoCode: 'RJT1', iataCode: null, prefectureCode: '11' },
    { officialName: '入間飛行場', aliases: [], icaoCode: 'RJTJ', iataCode: null, prefectureCode: '11' },
    {
        officialName: '成田国際空港',
        aliases: ['成田空港'],
        icaoCode: 'RJAA',
        iataCode: 'NRT',
        prefectureCode: '12',
    },
    { officialName: '館山飛行場', aliases: [], icaoCode: 'RJTE', iataCode: null, prefectureCode: '12' },
    { officialName: '木更津飛行場', aliases: [], icaoCode: 'RJTK', iataCode: null, prefectureCode: '12' },
    { officialName: '下総飛行場', aliases: [], icaoCode: 'RJTL', iataCode: null, prefectureCode: '12' },
    { officialName: '防衛省ヘリポート', aliases: [], icaoCode: 'RJAI', iataCode: null, prefectureCode: '13' },
    {
        officialName: '南鳥島飛行場',
        aliases: [],
        icaoCode: 'RJAM',
        iataCode: 'MUS',
        prefectureCode: '13',
    },
    { officialName: '新島空港', aliases: [], icaoCode: 'RJAN', iataCode: null, prefectureCode: '13' },
    { officialName: '父島ヘリポート', aliases: [], icaoCode: 'RJAO', iataCode: null, prefectureCode: '13' },
    {
        officialName: '硫黄島飛行場',
        aliases: [],
        icaoCode: 'RJAW',
        iataCode: 'IWO',
        prefectureCode: '13',
    },
    { officialName: '神津島空港', aliases: [], icaoCode: 'RJAZ', iataCode: null, prefectureCode: '13' },
    { officialName: '立川飛行場', aliases: [], icaoCode: 'RJTC', iataCode: null, prefectureCode: '13' },
    { officialName: '調布飛行場', aliases: [], icaoCode: 'RJTF', iataCode: null, prefectureCode: '13' },
    { officialName: '八丈島空港', aliases: [], icaoCode: 'RJTH', iataCode: 'HAC', prefectureCode: '13' },
    { officialName: '東京ヘリポート', aliases: [], icaoCode: 'RJTI', iataCode: null, prefectureCode: '13' },
    { officialName: '大島空港', aliases: [], icaoCode: 'RJTO', iataCode: 'OIM', prefectureCode: '13' },
    { officialName: '三宅島空港', aliases: [], icaoCode: 'RJTQ', iataCode: 'MYE', prefectureCode: '13' },
    {
        officialName: '東京国際空港',
        aliases: ['羽田空港'],
        icaoCode: 'RJTT',
        iataCode: 'HND',
        prefectureCode: '13',
    },
    { officialName: '横田飛行場', aliases: [], icaoCode: 'RJTY', iataCode: 'OKO', prefectureCode: '13' },
    {
        officialName: '厚木飛行場',
        aliases: [],
        icaoCode: 'RJTA',
        iataCode: 'NJA',
        prefectureCode: '14',
    },
    { officialName: 'キャンプ座間', aliases: [], icaoCode: 'RJTR', iataCode: null, prefectureCode: '14' },
    { officialName: '米海軍横須賀基地ヘリポート', aliases: [], icaoCode: 'RJTX', iataCode: null, prefectureCode: '14' },
    { officialName: '佐渡空港', aliases: [], icaoCode: 'RJSD', iataCode: 'SDS', prefectureCode: '15' },
    { officialName: '新潟空港', aliases: [], icaoCode: 'RJSN', iataCode: 'KIJ', prefectureCode: '15' },
    { officialName: '富山空港', aliases: [], icaoCode: 'RJNT', iataCode: 'TOY', prefectureCode: '16' },
    {
        officialName: '小松飛行場',
        aliases: ['小松空港'],
        icaoCode: 'RJNK',
        iataCode: 'KMQ',
        prefectureCode: '17',
    },
    { officialName: '能登空港', aliases: [], icaoCode: 'RJNW', iataCode: 'NTQ', prefectureCode: '17' },
    { officialName: '福井空港', aliases: [], icaoCode: 'RJNF', iataCode: 'FKJ', prefectureCode: '18' },
    { officialName: '松本空港', aliases: [], icaoCode: 'RJAF', iataCode: 'MMJ', prefectureCode: '20' },
    { officialName: '岐阜飛行場', aliases: [], icaoCode: 'RJNG', iataCode: null, prefectureCode: '21' },
    { officialName: '滝ヶ原飛行場', aliases: [], icaoCode: 'RJAT', iataCode: null, prefectureCode: '22' },
    { officialName: '浜松飛行場', aliases: [], icaoCode: 'RJNH', iataCode: null, prefectureCode: '22' },
    { officialName: '静岡空港', aliases: [], icaoCode: 'RJNS', iataCode: 'FSZ', prefectureCode: '22' },
    { officialName: '静浜飛行場', aliases: [], icaoCode: 'RJNY', iataCode: null, prefectureCode: '22' },
    { officialName: '中部国際空港', aliases: ['セントレア'], icaoCode: 'RJGG', iataCode: 'NGO', prefectureCode: '23' },
    {
        officialName: '名古屋飛行場',
        aliases: ['県営名古屋空港'],
        icaoCode: 'RJNA',
        iataCode: 'NKM',
        prefectureCode: '23',
    },
    { officialName: '明野飛行場', aliases: [], icaoCode: 'RJOE', iataCode: null, prefectureCode: '24' },
    { officialName: '舞鶴飛行場', aliases: [], icaoCode: 'RJBM', iataCode: null, prefectureCode: '26' },
    { officialName: '関西国際空港', aliases: ['関空空港'], icaoCode: 'RJBB', iataCode: 'KIX', prefectureCode: '27' },
    {
        officialName: '大阪国際空港',
        aliases: ['伊丹空港'],
        icaoCode: 'RJOO',
        iataCode: 'ITM',
        prefectureCode: '27',
    },
    { officialName: '八尾空港', aliases: [], icaoCode: 'RJOY', iataCode: null, prefectureCode: '27' },
    { officialName: '神戸空港', aliases: [], icaoCode: 'RJBE', iataCode: 'UKB', prefectureCode: '28' },
    { officialName: '但馬飛行場', aliases: ['但馬空港'], icaoCode: 'RJBT', iataCode: 'TJH', prefectureCode: '28' },
    { officialName: '南紀白浜空港', aliases: [], icaoCode: 'RJBD', iataCode: 'SHM', prefectureCode: '30' },
    { officialName: '美保飛行場', aliases: ['米子空港'], icaoCode: 'RJOH', iataCode: 'YGJ', prefectureCode: '31' },
    { officialName: '鳥取空港', aliases: [], icaoCode: 'RJOR', iataCode: 'TTJ', prefectureCode: '31' },
    { officialName: '隠岐空港', aliases: [], icaoCode: 'RJNO', iataCode: 'OKI', prefectureCode: '32' },
    { officialName: '出雲空港', aliases: [], icaoCode: 'RJOC', iataCode: 'IZO', prefectureCode: '32' },
    { officialName: '石見空港', aliases: [], icaoCode: 'RJOW', iataCode: 'IWJ', prefectureCode: '32' },
    { officialName: '岡南飛行場', aliases: [], icaoCode: 'RJBK', iataCode: null, prefectureCode: '33' },
    { officialName: '岡山空港', aliases: [], icaoCode: 'RJOB', iataCode: 'OKJ', prefectureCode: '33' },
    { officialName: '広島空港', aliases: [], icaoCode: 'RJOA', iataCode: 'HIJ', prefectureCode: '34' },
    { officialName: '山口宇部空港', aliases: [], icaoCode: 'RJDC', iataCode: 'UBJ', prefectureCode: '35' },
    {
        officialName: '防府飛行場',
        aliases: [],
        icaoCode: 'RJOF',
        iataCode: null,
        prefectureCode: '35',
    },
    { officialName: '岩国飛行場', aliases: [], icaoCode: 'RJOI', iataCode: null, prefectureCode: '35' },
    { officialName: '小月飛行場', aliases: [], icaoCode: 'RJOZ', iataCode: null, prefectureCode: '35' },
    { officialName: '小松島飛行場', aliases: [], icaoCode: 'RJOP', iataCode: null, prefectureCode: '36' },
    { officialName: '徳島飛行場', aliases: [], icaoCode: 'RJOS', iataCode: 'TKS', prefectureCode: '36' },
    { officialName: '高松空港', aliases: [], icaoCode: 'RJOT', iataCode: 'TAK', prefectureCode: '37' },
    { officialName: '松山空港', aliases: [], icaoCode: 'RJOM', iataCode: 'MYJ', prefectureCode: '38' },
    { officialName: '高知空港', aliases: [], icaoCode: 'RJOK', iataCode: 'KCZ', prefectureCode: '39' },
    { officialName: '芦屋飛行場', aliases: [], icaoCode: 'RJFA', iataCode: null, prefectureCode: '40' },
    { officialName: '福岡空港', aliases: [], icaoCode: 'RJFF', iataCode: 'FUK', prefectureCode: '40' },
    { officialName: '奈多ヘリポート', aliases: [], icaoCode: 'RJFH', iataCode: null, prefectureCode: '40' },
    { officialName: '北九州空港', aliases: [], icaoCode: 'RJFR', iataCode: 'KKJ', prefectureCode: '40' },
    { officialName: '築城飛行場', aliases: [], icaoCode: 'RJFZ', iataCode: null, prefectureCode: '40' },
    { officialName: '目達原飛行場', aliases: [], icaoCode: 'RJDM', iataCode: null, prefectureCode: '41' },
    { officialName: '佐賀空港', aliases: [], icaoCode: 'RJFS', iataCode: 'HSG', prefectureCode: '41' },
    { officialName: '壱岐空港', aliases: [], icaoCode: 'RJDB', iataCode: 'IKI', prefectureCode: '42' },
    { officialName: '上五島空港', aliases: [], icaoCode: 'RJDK', iataCode: null, prefectureCode: '42' },
    { officialName: '小値賀空港', aliases: [], icaoCode: 'RJDO', iataCode: null, prefectureCode: '42' },
    { officialName: '対馬空港', aliases: [], icaoCode: 'RJDT', iataCode: 'TSJ', prefectureCode: '42' },
    { officialName: '大村飛行場', aliases: [], icaoCode: 'RJDU', iataCode: null, prefectureCode: '42' },
    { officialName: '福江空港', aliases: [], icaoCode: 'RJFE', iataCode: 'FUJ', prefectureCode: '42' },
    { officialName: '長崎空港', aliases: [], icaoCode: 'RJFU', iataCode: 'NGS', prefectureCode: '42' },
    { officialName: '天草飛行場', aliases: ['天草空港'], icaoCode: 'RJDA', iataCode: 'AXJ', prefectureCode: '43' },
    { officialName: '熊本空港', aliases: [], icaoCode: 'RJFT', iataCode: 'KMJ', prefectureCode: '43' },
    { officialName: '大分空港', aliases: [], icaoCode: 'RJFO', iataCode: 'OIT', prefectureCode: '44' },
    { officialName: '宮崎空港', aliases: [], icaoCode: 'RJFM', iataCode: 'KMI', prefectureCode: '45' },
    { officialName: '新田原飛行場', aliases: [], icaoCode: 'RJFN', iataCode: null, prefectureCode: '45' },
    { officialName: '屋久島空港', aliases: [], icaoCode: 'RJFC', iataCode: 'KUM', prefectureCode: '46' },
    { officialName: '種子島空港', aliases: [], icaoCode: 'RJFG', iataCode: 'TNE', prefectureCode: '46' },
    { officialName: '鹿児島空港', aliases: [], icaoCode: 'RJFK', iataCode: 'KOJ', prefectureCode: '46' },
    { officialName: '鹿屋飛行場', aliases: [], icaoCode: 'RJFY', iataCode: null, prefectureCode: '46' },
    { officialName: '奄美空港', aliases: [], icaoCode: 'RJKA', iataCode: 'ASJ', prefectureCode: '46' },
    { officialName: '沖永良部空港', aliases: [], icaoCode: 'RJKB', iataCode: 'OKE', prefectureCode: '46' },
    { officialName: '喜界空港', aliases: [], icaoCode: 'RJKI', iataCode: 'KKX', prefectureCode: '46' },
    { officialName: '徳之島空港', aliases: [], icaoCode: 'RJKN', iataCode: 'TKN', prefectureCode: '46' },
    { officialName: '与論空港', aliases: [], icaoCode: 'RORY', iataCode: 'RNJ', prefectureCode: '46' },
    { officialName: '那覇空港', aliases: [], icaoCode: 'ROAH', iataCode: 'OKA', prefectureCode: '47' },
    { officialName: '嘉手納飛行場', aliases: [], icaoCode: 'RODN', iataCode: 'DNA', prefectureCode: '47' },
    { officialName: '石垣空港', aliases: [], icaoCode: 'ROIG', iataCode: 'ISG', prefectureCode: '47' },
    { officialName: '久米島空港', aliases: [], icaoCode: 'ROKJ', iataCode: 'UEO', prefectureCode: '47' },
    { officialName: '慶良間空港', aliases: [], icaoCode: 'ROKR', iataCode: 'KJP', prefectureCode: '47' },
    { officialName: '南大東空港', aliases: [], icaoCode: 'ROMD', iataCode: 'MMD', prefectureCode: '47' },
    { officialName: '宮古空港', aliases: [], icaoCode: 'ROMY', iataCode: 'MMY', prefectureCode: '47' },
    { officialName: '粟国空港', aliases: [], icaoCode: 'RORA', iataCode: 'AGJ', prefectureCode: '47' },
    { officialName: '伊江島空港', aliases: [], icaoCode: 'RORE', iataCode: 'IEJ', prefectureCode: '47' },
    { officialName: '波照間空港', aliases: [], icaoCode: 'RORH', iataCode: 'HTR', prefectureCode: '47' },
    { officialName: '北大東空港', aliases: [], icaoCode: 'RORK', iataCode: 'KTD', prefectureCode: '47' },
    { officialName: '下地島空港', aliases: [], icaoCode: 'RORS', iataCode: 'SHI', prefectureCode: '47' },
    { officialName: '多良間空港', aliases: [], icaoCode: 'RORT', iataCode: 'TRA', prefectureCode: '47' },
    { officialName: '普天間飛行場', aliases: [], icaoCode: 'ROTM', iataCode: null, prefectureCode: '47' },
    { officialName: '与那国空港', aliases: [], icaoCode: 'ROYN', iataCode: 'OGN', prefectureCode: '47' },
] satisfies JapanAirport[];

const normalizeValue = (value: string) => value.trim().toLocaleLowerCase('ja-JP');

export const searchAirports = (query: string, airports: JapanAirport[] = japanAirports) => {
    const normalizedQuery = normalizeValue(query);

    if (normalizedQuery === '') {
        return airports;
    }

    return airports.filter((airport) =>
        [airport.officialName, ...airport.aliases, airport.icaoCode, airport.iataCode ?? '']
            .filter((value) => value !== '')
            .map(normalizeValue)
            .some((value) => value.includes(normalizedQuery)),
    );
};
