version: '3'

services:
  nuxt:
    build: .
    image: hiroxto-net-nuxt
    tty: true
    command: yarn run dev
    volumes:
      - .:/app:cached
    ports:
      - "8080:3000"
    environment:
      - TZ
