version: '3'

services:
    app:
        build: .
        tty: true
        command: yarn run dev
        volumes:
            - .:/app:cached
        ports:
            - "5173:5173"
        environment:
            - TZ
