version: '3'

services:
    app:
        build: .
        tty: true
        command: yarn run dev
        volumes:
            - .:/app:cached
        ports:
            - "${APP_PORT:-8080}:8080"
        environment:
            - TZ
